### PR TITLE
remove file if not authorized

### PR DESCRIPTION
**Pull request by nbittich**

### CODE REVIEW

**Review by nvdk — COMMENTED** [review]
While exceptional, this would block the case where a user is allowed to upload files but not read them. So perhaps this needs to be behind some kind of flag?

**Comment by nbittich** [comment]
I've added `ALLOW_UPLOAD_WITHOUT_READ_ACCESS` (default to false)

**Comment by madnificent** [comment]
Code has been updated with two main changes in mind:
- renaming the environment variable to be a positive check and be backwards compatible
- adding support for the desired path where the triplestore informs us it could not write the data

Making the env var in a positive phrasing makes it a tad easier to grok what happens when it's set to false.  We also flipped the meaning of the env var so doing nothing makes the service behave as before (and thus coping with writing content to a drop area).

The second part implements the case where mu-authorization's `ERROR_ON_UNWRITTEN_DATA` is turned on.  This path now throws an error towards the user and removes the uploaded file.  This supports @nvdk 's drop area suggestion.

Other minor changes include reading all metadata rather than a specific set of metadata and changing the original code so errors are handled in one place.

**Comment by madnificent** [comment]
There's a feature build `semtech/mu-file-service:feature-validate-readable-metadata` which can be tested :)

**Review by MartijnBogaert — APPROVED** [review]

**Pull request merged**
